version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - CORS_ORIGINS=${CORS_ORIGINS}
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - dataviz-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXTAUTH_BACKEND_URL=${NEXTAUTH_BACKEND_URL}
    depends_on:
      - backend
    networks:
      - dataviz-network
    restart: unless-stopped

networks:
  dataviz-network:
    driver: bridge