services:
  # Backend service
  - type: web
    name: dataviz-backend
    env: python
    runtime: python-3.11
    buildCommand: |
      cd backend &&
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRATION_TIME
        value: "86400"
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: dataviz-frontend
          property: host

  # Frontend service
  - type: web
    name: dataviz-frontend
    env: node
    runtime: node-18
    buildCommand: |
      cd frontend &&
      npm install &&
      npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: dataviz-frontend
          property: host
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: dataviz-backend
          property: host